# Generated by Django 2.2.5 on 2021-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infoinsta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=128)),
                ('arroba', models.CharField(max_length=128)),
                ('biography', models.CharField(max_length=128)),
                ('followers', models.CharField(max_length=128)),
                ('followeds', models.CharField(max_length=128)),
                ('publications', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
    ]
