# Generated by Django 2.2.5 on 2021-03-03 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info1', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatnombres',
            fields=[
                ('first_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=128)),
                ('asd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info1.Infoinsta')),
            ],
        ),
    ]
