# Generated by Django 2.2.5 on 2021-02-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatnombres',
            name='id',
        ),
        migrations.AlterField(
            model_name='chatnombres',
            name='first_name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
