# Generated by Django 2.2.5 on 2021-03-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infoinsta',
            fields=[
                ('nick_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('arroba', models.CharField(max_length=128)),
                ('biography', models.CharField(max_length=128)),
                ('followers', models.CharField(max_length=128)),
                ('followeds', models.CharField(max_length=128)),
                ('publications', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
    ]
